GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/635fa0802fd5f2bbe93d424a

###


GET http://localhost:3001/api/notes/635fa0802fd5f2bbe93d425a


###


GET http://localhost:3001/api/notes/lkdfnflskgksfdgndf