

GET http://localhost:3001/api/notes

###

PUT http://localhost:3001/api/notes/635fa0802fd5f2bbe93d424a
Content-Type: application/json

{
  "userId": 3,
  "title": "Updated!",
  "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem, fugit facilis blanditiis id dicta optio molestias reiciendis vel minima! Perspiciatis dignissimos natus temporibus at laboriosam dolores itaque ipsa neque velit.",
  "important": true
}
###

PUT http://localhost:3001/api/notes/635fa0802fd5f2bbe93d425b
Content-Type: application/json

{
  "userId": 12,
  "title": "Wrong update!",
  "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem, fugit facilis blanditiis id dicta optio molestias reiciendis vel minima! Perspiciatis dignissimos natus temporibus at laboriosam dolores itaque ipsa neque velit.",
  "important": true
}
###

PUT http://localhost:3001/api/notes/3948043298509458
Content-Type: application/json

{
  "userId": 3,
  "title": "Wrong ID!",
  "body": "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quidem, fugit facilis blanditiis id dicta optio molestias reiciendis vel minima! Perspiciatis dignissimos natus temporibus at laboriosam dolores itaque ipsa neque velit.",
  "important": true
}